/**
 * Database type definitions for Dropin.
 *
 * In a connected project these would be auto-generated by:
 *   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.types.ts
 *
 * Manual types are maintained here until the Supabase project is linked.
 * Keep in sync with supabase/migrations/*.sql
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          logo_url: string | null;
          website_url: string | null;
          phone: string | null;
          email: string | null;
          address_line1: string | null;
          city: string | null;
          province: string | null;
          postal_code: string | null;
          country: string;
          status: "pending" | "active" | "suspended";
          approved_at: string | null;
          approved_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["organizations"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["organizations"]["Insert"]
        >;
      };
      org_memberships: {
        Row: {
          id: string;
          org_id: string;
          user_id: string;
          role: "owner" | "admin" | "member";
          invited_by: string | null;
          joined_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["org_memberships"]["Row"],
          "id" | "joined_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["org_memberships"]["Insert"]
        >;
      };
      facilities: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          slug: string;
          description: string | null;
          address_line1: string;
          city: string;
          province: string;
          postal_code: string;
          country: string;
          lat: number | null;
          lng: number | null;
          phone: string | null;
          email: string | null;
          website_url: string | null;
          photo_urls: string[];
          amenities: string[];
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["facilities"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["facilities"]["Insert"]>;
      };
      departments: {
        Row: {
          id: string;
          facility_id: string;
          org_id: string;
          name: string;
          slug: string;
          description: string | null;
          display_order: number;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["departments"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["departments"]["Insert"]>;
      };
      spaces: {
        Row: {
          id: string;
          org_id: string;
          facility_id: string;
          department_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          capacity: number | null;
          display_order: number;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["spaces"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["spaces"]["Insert"]>;
      };
      facility_maps: {
        Row: {
          id: string;
          org_id: string;
          facility_id: string;
          name: string;
          canvas_width: number;
          canvas_height: number;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["facility_maps"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["facility_maps"]["Insert"]
        >;
      };
      space_hotspots: {
        Row: {
          id: string;
          org_id: string;
          facility_map_id: string;
          space_id: string;
          shape: "rect";
          x: number;
          y: number;
          width: number;
          height: number;
          rotation: number;
          label: string | null;
          group_id: string | null;
          lane_index: number | null;
          preset_key: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["space_hotspots"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["space_hotspots"]["Insert"]
        >;
      };
      map_context_elements: {
        Row: {
          id: string;
          org_id: string;
          facility_map_id: string;
          kind: "zone" | "entrance";
          x: number;
          y: number;
          width: number;
          height: number;
          rotation: number;
          label: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["map_context_elements"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["map_context_elements"]["Insert"]
        >;
      };
      schedule_groups: {
        Row: {
          id: string;
          org_id: string;
          facility_id: string;
          department_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          sport_category: string;
          activity_type: "drop_in" | "registered" | "open_gym";
          age_group: string | null;
          skill_level: string | null;
          max_participants: number | null;
          cost_cents: number;
          cost_notes: string | null;
          photo_urls: string[];
          tags: string[];
          display_order: number;
          is_published: boolean;
          schedule_type: "time_block" | "continuous";
          continuous_hours_note: string | null;
          source: "manual" | "scraped" | "imported";
          source_url: string | null;
          external_id: string | null;
          last_synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["schedule_groups"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["schedule_groups"]["Insert"]
        >;
      };
      session_templates: {
        Row: {
          id: string;
          org_id: string;
          schedule_group_id: string;
          name: string;
          color: string | null;
          default_duration_minutes: number;
          default_space_id: string | null;
          display_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["session_templates"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["session_templates"]["Insert"]
        >;
      };
      sessions: {
        Row: {
          id: string;
          schedule_group_id: string;
          org_id: string;
          template_id: string | null;
          rrule: string;
          dtstart: string;
          dtend_time: string;
          timezone: string;
          valid_from: string;
          valid_until: string | null;
          location_detail: string | null;
          space_id: string | null;
          source: "manual" | "scraped" | "imported";
          source_url: string | null;
          external_id: string | null;
          last_synced_at: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["sessions"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["sessions"]["Insert"]>;
      };
      session_exceptions: {
        Row: {
          id: string;
          session_id: string;
          org_id: string;
          exception_date: string;
          exception_type: "cancelled" | "modified" | "added";
          modified_start: string | null;
          modified_end: string | null;
          reason: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["session_exceptions"]["Row"],
          "id" | "created_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["session_exceptions"]["Insert"]
        >;
      };
      widget_configs: {
        Row: {
          id: string;
          org_id: string;
          primary_color: string;
          secondary_color: string;
          font_family: string;
          show_cost: boolean;
          show_location: boolean;
          show_age_group: boolean;
          time_range_start: string;
          time_range_end: string;
          program_ids: string[] | null;
          custom_title: string | null;
          allowed_templates: ("grid" | "list" | "map" | "floorplan")[];
          facility_id: string | null;
          department_id: string | null;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["widget_configs"]["Row"],
          "id"
        >;
        Update: Partial<
          Database["public"]["Tables"]["widget_configs"]["Insert"]
        >;
      };
      subscriptions: {
        Row: {
          id: string;
          org_id: string;
          stripe_customer_id: string;
          stripe_subscription_id: string | null;
          plan_tier: "free" | "pro" | "enterprise";
          status: string;
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["subscriptions"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["subscriptions"]["Insert"]
        >;
      };
      analytics_events: {
        Row: {
          id: string;
          org_id: string;
          event_type:
            | "widget_view"
            | "program_click"
            | "facility_view"
            | "schedule_view";
          schedule_group_id: string | null;
          facility_id: string | null;
          referrer_url: string | null;
          user_agent: string | null;
          ip_hash: string | null;
          occurred_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["analytics_events"]["Row"],
          "id"
        >;
        Update: never;
      };
      scraping_configs: {
        Row: {
          id: string;
          org_id: string;
          facility_id: string | null;
          source_url: string;
          platform: "xplor" | "activenet" | "nextrec" | "generic";
          schedule_cron: string;
          is_active: boolean;
          last_run_at: string | null;
          next_run_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["scraping_configs"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["scraping_configs"]["Insert"]
        >;
      };
      scraping_jobs: {
        Row: {
          id: string;
          config_id: string;
          org_id: string;
          status: "pending" | "running" | "completed" | "failed";
          triggered_by: "scheduler" | "manual";
          started_at: string | null;
          completed_at: string | null;
          programs_found: number;
          sessions_found: number;
          conflicts_count: number;
          error_message: string | null;
          raw_data: Json | null;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["scraping_jobs"]["Row"],
          "id" | "created_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["scraping_jobs"]["Insert"]
        >;
      };
      scraping_conflicts: {
        Row: {
          id: string;
          job_id: string;
          org_id: string;
          entity_type: "program" | "session";
          entity_id: string | null;
          field_name: string;
          current_value: string | null;
          scraped_value: string | null;
          resolution: "accepted" | "rejected" | "ignored" | null;
          resolved_by: string | null;
          resolved_at: string | null;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["scraping_conflicts"]["Row"],
          "id" | "created_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["scraping_conflicts"]["Insert"]
        >;
      };
      staff_invitations: {
        Row: {
          id: string;
          org_id: string;
          email: string;
          role: "owner" | "admin" | "member";
          token: string;
          invited_by: string;
          accepted_at: string | null;
          expires_at: string;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["staff_invitations"]["Row"],
          "id" | "token" | "created_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["staff_invitations"]["Insert"]
        >;
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
};
