import type { Database } from "./database.types";

export type Session = Database["public"]["Tables"]["sessions"]["Row"];
export type SessionException =
  Database["public"]["Tables"]["session_exceptions"]["Row"];
export type ScheduleGroup = Database["public"]["Tables"]["schedule_groups"]["Row"];
export type Facility = Database["public"]["Tables"]["facilities"]["Row"];
export type FacilityMap = Database["public"]["Tables"]["facility_maps"]["Row"];
export type SpaceHotspot = Database["public"]["Tables"]["space_hotspots"]["Row"];
export type MapContextElement =
  Database["public"]["Tables"]["map_context_elements"]["Row"];

/** A hotspot joined with its space's display info, as returned to the public floorplan view. */
export type SpaceHotspotWithSpace = SpaceHotspot & {
  spaceName: string;
  spaceCapacity: number | null;
};

/**
 * A concrete, expanded occurrence of a recurring session.
 * Generated by lib/rrule/expand.ts from a Session row + its exceptions.
 */
export type ExpandedSession = {
  /** Unique key for this specific occurrence: `${sessionId}_${date}` */
  key: string;
  sessionId: string;
  orgId: string;

  /**
   * This occurrence's local wall-clock start/end, stored as literal
   * UTC-labelled digits with no real instant meaning (see
   * dropin/docs/RESUME-timezone-removal.md and rrule/README.md). Read with
   * getUTCHours()/getUTCDate()/etc — via `formatSessionTime`/
   * `formatSessionDayFull`/`sessionDateString` (src/lib/utils/dates.ts) for
   * display — never through the runtime-local getters `formatTime`/
   * `formatDayFull`/`new Date().toDateString()` use, which would read a
   * different, wrong wall-clock value on any machine not itself in UTC.
   */
  start: Date;
  end: Date;

  /** Denormalized schedule group info for display without extra fetches */
  scheduleGroupId: string;
  scheduleGroupName: string;
  sportCategory: string;
  activityType: ScheduleGroup["activity_type"];
  costCents: number;
  costNotes: string | null;
  ageGroup: string | null;
  skillLevel: string | null;
  maxParticipants: number | null;

  /** Denormalized facility info */
  facilityId: string;
  facilityName: string;

  /** Denormalized department info — null if the schedule group has no department */
  departmentId: string | null;
  departmentName: string | null;

  /** Structured spaces within the facility this session occupies, if any (e.g. all of Lanes 1-4 for a shared Lap Swim block) */
  spaceIds: string[];
  spaceNames: string[];

  /**
   * Which facility configuration(s) this occurrence implies — the state the
   * building has to be in for it to happen (migration 048).
   *
   * Derived from the claimed spaces, never stored on the session: eight
   * long-course lanes all point at "Long Course (50m)", so this is the distinct
   * set. **Empty is the normal case** — every space at a facility that has
   * described no configurations exists in all of them, so nothing to say.
   * More than one entry means the session claims lanes from two states of the
   * building at once, which is a mistake worth rendering as one. Name it
   * through `configurationLabel()` (src/lib/spaces/configurations.ts).
   */
  configurationIds: string[];
  configurationNames: string[];

  /** Session template this occurrence was placed from, if any (see session_templates) */
  templateId: string | null;
  templateName: string | null;
  templateColor: string | null;

  /**
   * What this booking does to the space (migration 046). 'drop_in' is
   * residual — it occupies whatever is not exclusively claimed.
   */
  occupancyKind: Session["occupancy_kind"];
  /**
   * Who may know this session's name. A public caller can legitimately see
   * this value ('reserved' is what tells a renderer to style the block as
   * withheld); what a public caller never sees is `holderName`. 'internal'
   * never reaches a public caller at all — RLS drops the row.
   */
  disclosure: Session["disclosure"];
  /**
   * Who actually holds the space ("Island Swimming"), from `session_internal`.
   *
   * **Null for every caller outside the owning org**, and not by filtering —
   * the table has no public-read policy, and /api/sessions/expand only queries
   * it for org members in the first place. Render it through
   * `sessionDisplayLabel()` (src/lib/sessions/occupancy.ts) rather than
   * reaching for it directly, so a public surface cannot be made to leak one
   * by a later edit.
   */
  holderName: string | null;
  /** Staff-only setup note ("soft lane ropes, polo nets"). Same guarantee as holderName. */
  setupNotes: string | null;

  /** Free-text location note — shown alongside the space, e.g. entry instructions */
  locationDetail: string | null;

  /**
   * Set when this occurrence was modified by a session_exception.
   * 'cancelled' occurrences are excluded from the output entirely.
   */
  isModified?: boolean;
  modificationNote?: string | null;
};

/** Which visual layout a schedule is rendered as. */
export type ScheduleTemplate = "grid" | "list" | "map" | "floorplan" | "board";

/**
 * Parameters for expanding sessions across a date range.
 *
 * This was once strictly week-shaped (`weekStart`/`weekEnd`). Nothing about
 * expansion was ever week-specific — the RRULE is evaluated between two
 * instants — so the range is arbitrary, and the caller decides whether that's
 * a week or a month. `/api/sessions/expand` caps how wide it may be.
 */
export type RangeExpandParams = {
  rangeStart: Date;
  rangeEnd: Date;
  orgId?: string;
  facilityId?: string;
  departmentId?: string;
  scheduleGroupId?: string;
};

/** Grid position for rendering in the weekly schedule grid */
export type GridPosition = {
  /** Column index (0 = Sunday ... 6 = Saturday) */
  dayIndex: number;
  /** Minutes from the grid's start time (e.g. 360 = 6:00 AM if grid starts at midnight) */
  startMinute: number;
  /** Duration in minutes */
  durationMinutes: number;
};
