import type { Database } from "./database.types";

export type Session = Database["public"]["Tables"]["sessions"]["Row"];
export type SessionException =
  Database["public"]["Tables"]["session_exceptions"]["Row"];
export type Program = Database["public"]["Tables"]["programs"]["Row"];
export type Facility = Database["public"]["Tables"]["facilities"]["Row"];

/**
 * A concrete, expanded occurrence of a recurring session.
 * Generated by lib/rrule/expand.ts from a Session row + its exceptions.
 */
export type ExpandedSession = {
  /** Unique key for this specific occurrence: `${sessionId}_${date}` */
  key: string;
  sessionId: string;
  programId: string;
  orgId: string;

  /** Absolute start datetime for this occurrence */
  start: Date;
  /** Absolute end datetime for this occurrence */
  end: Date;

  /** Denormalized program info for display without extra fetches */
  programName: string;
  sportCategory: string;
  activityType: Program["activity_type"];
  costCents: number;
  costNotes: string | null;
  ageGroup: string | null;
  skillLevel: string | null;
  maxParticipants: number | null;

  /** Denormalized facility info */
  facilityId: string;
  facilityName: string;

  /** Optional sub-location within facility (e.g. "Lane 3", "Rink B") */
  locationDetail: string | null;

  /** Data origin — used to show staleness warnings on scraped sessions */
  source: Session["source"];
  lastSyncedAt: string | null;

  /**
   * Set when this occurrence was modified by a session_exception.
   * 'cancelled' occurrences are excluded from the output entirely.
   */
  isModified?: boolean;
  modificationNote?: string | null;
};

/** Parameters for expanding sessions into a week view */
export type WeekExpandParams = {
  weekStart: Date;
  weekEnd: Date;
  orgId?: string;
  facilityId?: string;
  programId?: string;
};

/** Grid position for rendering in the weekly schedule grid */
export type GridPosition = {
  /** Column index (0 = Monday ... 6 = Sunday) */
  dayIndex: number;
  /** Minutes from the grid's start time (e.g. 360 = 6:00 AM if grid starts at midnight) */
  startMinute: number;
  /** Duration in minutes */
  durationMinutes: number;
};
